openapi: 3.0.1
info:
  contact:
    email: otae@fundaciobit.org
    name: Departament de Govern Digital a la Fundació Bit
    url: http://otae.fundaciobit.org
  description: Conjunt de Serveis REST de DemoGenApp per ser accedits des de l'interior
  license:
    name: License Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  title: API REST INTERNA de DemoGenApp
  version: 1.0.0
externalDocs:
  description: Java Client (GovernIB Github)
  url: https://github.com/GovernIB/demogenapp/tree/demogenapp-1.0/demogenapp-api-interna-client
servers:
- url: /demogenappapi/interna
- url: http://localhost:8080/demogenappapi/interna
- url: https://dev.caib.es/demogenappapi/interna
- url: https://proves.caib.es/demogenappapi/interna
- url: https://se.caib.es/demogenappapi/interna
- url: https://www.caib.es/demogenappapi/interna
tags:
- description: Exemple de Servei JSON d'accés Públic
  name: ExemplePublicService
- description: Exemple de Servei de Dades Reutilitzables emprant paginació i retorn
    complet de dades
  name: ExempleServei
- description: Notificacions a l'APP de Carpeta (missateg a Mòbil)
  name: Notificacions
paths:
  /public/exemplepublic/versio:
    get:
      operationId: versio
      parameters:
      - description: Codi de l'idioma
        example: ca
        explode: true
        in: query
        name: idioma
        required: false
        schema:
          pattern: ^ca|es$
          type: string
        style: form
      responses:
        "404":
          content:
            application/json: {}
          description: Paràmetres incorrectes
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExamplePojo'
          description: Versió i idioma
      summary: Versio de l'Aplicació
      tags:
      - Versió
      x-accepts: application/json
  /public/exempleservei/exempleconsultacompleta:
    get:
      operationId: exempleconsultacompleta
      parameters:
      - description: Filtre pel Nom de l'objecte ExempleInfo. Opcional.
        explode: true
        in: query
        name: name
        required: false
        schema:
          type: string
        style: form
      - description: Filtre Data d'inici de la consulta. Opcional. Format yyyy-MM-dd
          (ISO 8601)
        example: 2023-07-19
        explode: true
        in: query
        name: startdate
        required: false
        schema:
          pattern: "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\\
            d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29))$"
          type: string
        style: form
      - description: Filtre Data final de la consulta. Opcional. Format  yyyy-MM-dd
          (ISO 8601)
        example: 2024-12-31
        explode: true
        in: query
        name: enddate
        required: false
        schema:
          pattern: "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\\
            d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29))$"
          type: string
        style: form
      - description: Idioma en que retornar les dades. Opcional.
        explode: true
        in: query
        name: language
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlistaDeExempleInfoCompleta'
          description: Operació realitzada correctament
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Paràmetres incorrectes
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Error no controlat
      summary: Retorna tots els elements d'informació d'exemple d'una vegada
      tags:
      - ExempleServei
      x-accepts: application/json
  /public/exempleservei/exempleconsultapaginada:
    get:
      operationId: consultapaginada
      parameters:
      - description: Filtre pel Nom de l'objecte ExempleInfo. Opcional.
        explode: true
        in: query
        name: name
        required: false
        schema:
          type: string
        style: form
      - description: Filtre Data d'inici de la consulta. Opcional. Format yyyy-MM-dd
          (ISO 8601)
        example: 2023-07-19
        explode: true
        in: query
        name: startdate
        required: false
        schema:
          pattern: "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\\
            d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29))$"
          type: string
        style: form
      - description: Filtre Data final de la consulta. Opcional. Format yyyy-MM-dd
          (ISO 8601)
        example: 2024-12-31
        explode: true
        in: query
        name: enddate
        required: false
        schema:
          pattern: "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\\
            d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29))$"
          type: string
        style: form
      - description: Numero de pàgina quan el llistat és paginat. Opcional. Per defecte
          1.
        explode: true
        in: query
        name: page
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - description: Número d'elements a retornar per pàgina. Opcional. Per defecte
          15
        explode: true
        in: query
        name: page-size
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - description: Idioma en que retornar les dades. Opcional.
        explode: true
        in: query
        name: language
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlistaDeExempleInfoPaginada'
          description: Operació realitzada correctament
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Paràmetres incorrectes
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Error no controlat
      summary: Retorna informació d'exemple paginada
      tags:
      - ExempleServei
      x-accepts: application/json
  /secure/exempleenum/list:
    get:
      operationId: list
      parameters:
      - description: "Data d'inici, en format yyyy-MM-dd (ISO 8601), a partir de la\
          \ qual volem obtenir dades"
        example: 2022-08-29
        explode: true
        in: query
        name: inici
        required: false
        schema:
          type: string
        style: form
      - description: "Data fi, en format yyyy-MM-dd (ISO 8601), fins la qual volem\
          \ tenir dades"
        example: 2023-12-31
        explode: true
        in: query
        name: fi
        required: false
        schema:
          type: string
        style: form
      - description: Pàgina de la que es volen obtenir les dades. Comença per 1.
        example: 1
        explode: true
        in: query
        name: page
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - description: Quantitat d'elements a retornar
        example: 10
        explode: true
        in: query
        name: pagesize
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - description: Idioma en que s'han de retornar les dades(Només suportat 'ca'
          o 'es')
        examples:
          Català:
            description: Català
            value: ca
          Castellano:
            description: Castellano
            value: es
        explode: true
        in: query
        name: language
        required: false
        schema:
          type: string
        style: form
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: "EFIB: Paràmetres incorrectes"
        "401":
          content:
            application/json:
              schema:
                type: string
          description: "EFIB: No Autenticat"
        "403":
          content:
            application/json:
              schema:
                type: string
          description: "EFIB: No Autoritzat"
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: "EFIB: Error durant la consulta de les dades obertes"
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TipusDocumentalsPaginacio'
          description: "EFIB: Retornades dades obertes correctament"
      security:
      - BasicAuth: []
      summary: Retorna un llistat de tipus documentals
      tags:
      - Notificacions
      x-accepts: application/json
  /secure/exempleenum/sendnotificationtomobile:
    get:
      operationId: sendNotificationToMobile
      parameters:
      - description: Exemple de parametre Llistat d'Strings
        explode: true
        in: query
        name: notificationParameters
        required: true
        schema:
          items:
            type: string
          type: array
        style: form
      - description: Idioma en que s'enviaran els missatges d'error
        example: ca
        explode: true
        in: query
        name: langError
        required: true
        schema:
          pattern: ^ca|es$
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendMessageResult'
          description: Operació realitzada correctament
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Paràmetres incorrectes
        "401":
          content:
            application/json:
              schema:
                type: string
          description: No Autenticat
        "403":
          content:
            application/json:
              schema:
                type: string
          description: No Autoritzat
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestExceptionInfo'
          description: Error no controlat
      security:
      - BasicAuth: []
      summary: Envia un missatge al mòbil del ciutada a traves de l'App de Carpeta.
      tags:
      - Notificacions
      x-accepts: application/json
components:
  schemas:
    ExamplePojo:
      example:
        versio: versio
      properties:
        versio:
          type: string
      type: object
    ExempleInfo:
      description: Model de dades de Informació bàsica a retornar.
      example:
        date: 2000-01-23T04:56:07.000+00:00
        itemID: 6
        name: name
        value: value
      properties:
        itemID:
          description: Identificador intern de l'objecte
          format: int64
          type: integer
        name:
          description: Nom de l'entrada
          type: string
        value:
          description: Valor de l'entrada
          type: string
        date:
          description: Data en que es va fer crear aquest element
          format: date-time
          pattern: yyyy-MM-dd'T'HH:mm:ss
          type: string
      required:
      - date
      - itemID
      - name
      type: object
    LlistaDeExempleInfoCompleta:
      example:
        data:
        - date: 2000-01-23T04:56:07.000+00:00
          itemID: 6
          name: name
          value: value
        - date: 2000-01-23T04:56:07.000+00:00
          itemID: 6
          name: name
          value: value
        name: name
        total-count: 0
        date-download: date-download
      properties:
        name:
          description: Nom descriptiu del que s'està retornant
          type: string
        total-count:
          description: Número total d'elements
          format: int32
          type: integer
        date-download:
          description: Data i hora en que s'han retornat les dades. Format ISO-8601
          pattern: "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\\
            d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\\
            d|2[0-3]):[0-5]\\d:[0-5]\\d(?:Z|[+-][01]\\d:[0-5]\\d)$"
          type: string
        data:
          description: Elements retornats. Pot retornar un null o una llista bida
            si no hi ha elements.
          items:
            $ref: '#/components/schemas/ExempleInfo'
          type: array
      required:
      - date-download
      - name
      - total-count
      type: object
    RestExceptionInfo:
      description: Estructura de dades utilitzada per passar informació d'un error
      properties:
        code:
          description: Codi de HTTP de l'error. Veure https://en.wikipedia.org/wiki/List_of_HTTP_status_codes.
          format: int32
          type: integer
        errorMessage:
          description: Missatge de l'error
          type: string
        stackTrace:
          description: Stacktrace de l'excepció si n'hi hagués.
          type: string
        causeException:
          description: Tipus de l'excepció origen (cause) si n'hi hagués.
          type: string
        causeStackTrace:
          description: Stacktrace de l'excepció origen (cause) si n'hi hagués.
          type: string
      required:
      - code
      - errorMessage
      type: object
    LlistaDeExempleInfoPaginada:
      example:
        next: next
        page-size: 6
        data:
        - date: 2000-01-23T04:56:07.000+00:00
          itemID: 6
          name: name
          value: value
        - date: 2000-01-23T04:56:07.000+00:00
          itemID: 6
          name: name
          value: value
        name: name
        total-count: 5
        items-returned: 5
        page: 0
        total-pages: 1
        date-download: date-download
      properties:
        name:
          description: Nom descriptiu del que s'està retornant
          type: string
        page:
          description: Número pàgina. Comença per 1.
          format: int32
          type: integer
        page-size:
          description: Mida de pàgina
          format: int32
          type: integer
        total-pages:
          description: Número total de pàgines
          format: int32
          type: integer
        total-count:
          description: Número total d'elements
          format: int32
          type: integer
        items-returned:
          description: Numero d'elements retornats
          format: int32
          type: integer
        next:
          description: "Si hi ha més elements, llavors retorna la URL a la següent\
            \ pàgina de dades."
          type: string
        date-download:
          description: Data i hora en que s'han retornat les dades. Format ISO-8601
          pattern: "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\\
            d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\\
            d|2[0-3]):[0-5]\\d:[0-5]\\d(?:Z|[+-][01]\\d:[0-5]\\d)$"
          type: string
        data:
          description: Elements retornats. Pot retornar un null o una llista bida
            si no hi ha elements.
          items:
            $ref: '#/components/schemas/ExempleInfo'
          type: array
      required:
      - date-download
      - items-returned
      - name
      - page
      - page-size
      - total-count
      - total-pages
      type: object
    TipusDocumentalsPaginacio:
      example:
        totalcount: 5
        data:
        - data
        - data
        pagesize: 6
        page: 0
        totalpages: 1
      properties:
        page:
          description: Número pàgina. Comença per 1.
          format: int32
          type: integer
        pagesize:
          description: Mida de pàgina
          format: int32
          type: integer
        totalpages:
          description: Número total de pàgines
          format: int32
          type: integer
        totalcount:
          description: Numero total d'elements
          format: int32
          type: integer
        data:
          description: Elements retornats
          items:
            description: Elements retornats
            type: string
          type: array
      required:
      - data
      - page
      - pagesize
      - totalcount
      - totalpages
      type: object
    SendMessageResult:
      example:
        code: null
        message: message
      properties:
        code:
          $ref: '#/components/schemas/SendMessageResultCode'
        message:
          description: Missatge si hi ha error
          type: string
      type: object
    SendMessageResultCode:
      description: Codi resultat de l'operació
      enum:
      - OK
      - UNKNOWN_ERROR
      - NOTIFICATION_CODE_DO_NOT_EXIST
      - NOTIFICATION_CODE_DISABLED
      - ENTITYCODE_DO_NOT_EXIST
      - ENTITY_DISABLED
      - PLUGIN_DISABLED
      - PLUGIN_ENTITY_DO_NOT_EXIST
      - PLUGIN_ENTITY_DISABLED
      - CITIZEN_DO_NOT_EXIST
      - ERROR_SENDING_NOTIFICATION
      type: string
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http

